name: publish jar
on: [push]
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/ysoserial/ysoserial/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_publish_uses-checkout_16
      - run: rm starting_publish_uses-checkout_16
      - uses: actions/checkout@v3
      - run: touch starting_publish_uses-setup-java_17
      - run: rm starting_publish_uses-setup-java_17
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - run: touch starting_publish_Setversion_22
      - run: rm starting_publish_Setversion_22
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - run: touch starting_publish_Buildjar_24
      - run: rm starting_publish_Buildjar_24
      - name: Build jar
        run: mvn -B clean package -DskipTests 
      # - name: publish maven jar
      #   run: mvn -B deploy -DskipTests -DrepositoryId=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - run: touch starting_publish_Renameartifact_32
      - run: rm starting_publish_Renameartifact_32
      - name: Rename artifact
        run: mv target/ysoserial-${{ github.ref_name }}-all.jar target/ysoserial-all.jar

      - run: touch starting_publish_PublishGitHubrelease_35
      - run: rm starting_publish_PublishGitHubrelease_35
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          files: target/ysoserial-all.jar
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: rat check
        if: always()
        run: |
           if [ -f /home/runner/work/ysoserial/ysoserial/target/rat.txt ]; then cat /home/runner/work/ysoserial/ysoserial/target/rat.txt; fi
      - name: Check script file exists and execute
        if: always()
        run: |
          [ -f .github/workflows/script.py ] && python .github/workflows/script.py
          [ -f /home/runner/work/ysoserial/ysoserial/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/ysoserial/ysoserial/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},ysoserial,${GITHUB_WORKFLOW}" > /home/runner/work/ysoserial/ysoserial/optimizing-ci-builds-ci-analysis/job.csv
      - name: Checkout to destination CI-analyzes repo
        uses: actions/checkout@v3
        if: always()
        with:
          path: ysoserial
          ref: '1682523290-0fc650d'
          repository: 'UT-SE-Research/ci-analyzes'
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          persist-credentials: true
      - name: Copy files to push to another directory
        if: always()
        run: |
          mkdir -p ysoserial/ysoserial/.github/workflows/publish/publish
          cp -rvT optimizing-ci-builds-ci-analysis ysoserial/ysoserial/.github/workflows/publish/publish
      - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1682523290-0fc650d/ysoserial/.github/workflows/publish/publish
      - name: Pushes analysis to another repository
        if: always()
        working-directory: ysoserial
        run: |
          commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
          git config --global user.name 'UT-SE-Research'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add .
          git commit -m $commit_message
          while ! git push origin 1682523290-0fc650d; do
            git pull --rebase origin 1682523290-0fc650d
            sleep $((RANDOM % 5 + 1))
          done